### PR TITLE
Update Docker CI plugin versions and support multi-platform builds

### PR DESCRIPTION
**Pull request by johnclary**
In service of:
- https://github.com/cityofaustin/atd-data-tech/issues/12882

~Well, Microsoft doesn't make it easy to run their SQL server driver on Applie Silicon. I tried a few different approaches, but ultimately found that I could at least build/run this image locally by specifying the AMD platform during build.

Once the Github action builds and pushes, I'm not _positive_ M1 users will be able to pull and run it. You may have to build locally. This stuff is over my head :/~

Thank you @frankhereford for getting this working!

### CODE REVIEW

**Comment by johnclary** [comment]
bleh, this did not build for me locally because of a compatibility issue with `pymssql`. i will try to sort this out...

**Comment by johnclary** [comment]
Folks—this is ready for review: plz see my update in the PR description 🙏

**Comment by frankhereford** [comment]
I worked on the building error a little, and I think I have it working. It's building on my mac at least 🤞. I made a patch for you if you'd like it: https://github.com/cityofaustin/atd-kits/pull/10

**Comment by johnclary** [comment]
thank you @frankhereford !

**Pull request merged**
